name: .NET Desktop CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build Application
      run: dotnet build --configuration ${{ matrix.configuration }} XPSLauncher.sln

    - name: Run Tests
      run: dotnet test --configuration ${{ matrix.configuration }} XPSLauncher/XPSLauncher.csproj
